- name: Build Resume
  on:
    push:
      branches:
        - master
      # file paths to consider in the event. Optional; defaults to all.
      paths:
        - 'resume.md'
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - name: Make
      run: make
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Rebuild resume
